
const countriesAndCities = [
  {
    country: 'Argentina',
    cities: [
      'Buenos Aires', 
      'Córdoba', 
      'Rosario', 
      'Mendoza', 
      'La Plata', 
      'Tucumán', 
      'Mar del Plata', 
      'Salta', 
      'Santa Fe', 
      'San Juan', 
      'Neuquén', 
      'Bahía Blanca', 
      'Quilmes', 
      'Paraná', 
      'San Luis', 
      'Posadas', 
      'Santiago del Estero', 
      'Corrientes', 
      'San Salvador de Jujuy', 
      'Resistencia'
    ]
  },
      {
      country: 'Mexico',
      cities: [
        'Acapulco', 
        'Aguascalientes', 
        'Cancún', 
        'CDMX', 
        'Chihuahua', 
        'Ciudad Juarez', 
        'Culiacán', 
        'Durango', 
        'Guanajuato', 
        'Guadalajara', 
        'Hermosillo', 
        'Leon', 
        'Mérida', 
        'Mexicali', 
        'Monterrey', 
        'Morelia', 
        'Oaxaca', 
        'Puebla', 
        'Puerto Vallarta', 
        'Querétaro', 
        'San Luis Potosí', 
        'San Miguel de Allende', 
        'Santiago de Querétaro', 
        'Tijuana', 
        'Toluca', 
        'Torreon', 
        'Tuxtla Gutiérrez', 
        'Veracruz', 
        'Villahermosa', 
        'Zapopan'
      ]
    },
    {
      country: 'USA',
      cities: [
        'Albuquerque', 
        'Arlington', 
        'Atlanta', 
        'Austin', 
        'Baltimore', 
        'Boston', 
        'Charlotte', 
        'Chicago', 
        'Colorado Springs', 
        'Columbus', 
        'Dallas', 
        'Denver', 
        'Detroit', 
        'El Paso', 
        'Fort Worth', 
        'Fresno', 
        'Houston', 
        'Indianapolis', 
        'Jacksonville', 
        'Kansas City', 
        'Las Vegas', 
        'Long Beach', 
        'Los Angeles', 
        'Louisville', 
        'Memphis', 
        'Mesa', 
        'Miami', 
        'Milwaukee', 
        'Minneapolis', 
        'Nashville', 
        'New Orleans', 
        'New York', 
        'Oakland', 
        'Oklahoma City', 
        'Omaha', 
        'Philadelphia', 
        'Phoenix', 
        'Portland', 
        'Raleigh', 
        'Sacramento', 
        'San Antonio', 
        'San Diego', 
        'San Francisco', 
        'San Jose', 
        'Seattle', 
        'Tucson', 
        'Tulsa', 
        'Virginia Beach', 
        'Washington D.C.', 
        'Wichita'
      ]
    },
  
    
    
  ];
  
  module.exports = countriesAndCities;
  